#ifndef __GENERAL_H__
#define __GENERAL_H__

#include <prev/common/Common.h>

namespace prev_test {
constexpr auto TAG_LIGHT{ "Light" };
constexpr auto TAG_MAIN_LIGHT{ "MainLight" };
constexpr auto TAG_SHADOW{ "Shadow" };
constexpr auto TAG_CAMERA{ "Camera" };
constexpr auto TAG_MAIN_CAMERA{ "MainCamera" };
constexpr auto TAG_PLAYER{ "Player" };

enum class SceneNodeFlags {
    TRANSFORM_COMPONENT,
    RAYCASTER_COMPONENT,
    RENDER_COMPONENT,
    RENDER_NORMAL_MAPPED_COMPONENT,
    RENDER_PARALLAX_MAPPED_COMPONENT,
    RENDER_CONE_STEP_MAPPED_COMPONENT,
    ANIMATION_RENDER_COMPONENT,
    ANIMATION_NORMAL_MAPPED_RENDER_COMPONENT,
    ANIMATION_PARALLAX_MAPPED_RENDER_COMPONENT,
    ANIMATION_CONE_STEP_MAPPED_RENDER_COMPONENT,
    FONT_RENDER_COMPONENT,
    SKYBOX_RENDER_COMPONENT,
    TERRAIN_MANAGER_COMPONENT,
    TERRAIN_RENDER_COMPONENT,
    TERRAIN_NORMAL_MAPPED_RENDER_COMPONENT,
    TERRAIN_PARALLAX_MAPPED_RENDER_COMPONENT,
    TERRAIN_CONE_STEP_MAPPED_RENDER_COMPONENT,
    CAMERA_COMPONENT,
    SHADOWS_COMPONENT,
    LIGHT_COMPONENT,
    WATER_REFLECTION_RENDER_COMPONENT,
    WATER_REFRACTION_RENDER_COMPONENT,
    WATER_RENDER_COMPONENT,
    LENS_FLARE_RENDER_COMPONENT,
    SUN_RENDER_COMPONENT,
    BOUNDING_VOLUME_COMPONENT,
    SELECTABLE_COMPONENT,
    PARTICLE_SYSTEM_COMPONENT,
    CLOUDS_COMPONENT,
    SKY_RENDER_COMPONENT,
    TIME_COMPONENT,
    _
};
} // namespace prev_test

#endif