name: Linux (Wayland) - CI Build/Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
          - compiler: clang
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
        sudo apt update
        sudo apt-get install -y vulkan-sdk libminizip-dev libstdc++6 libc6-dev build-essential libwayland-dev ninja-build

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Compile Shaders
      run: |
        python3 Scripts/compile_shaders.py --spirv --max-view-count 1

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -G Ninja \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DENABLE_XCB=OFF \
        -DENABLE_WAYLAND=ON \
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Create Artifact
      run: |
        mkdir build-linux-wayland-${{ matrix.compiler }}
        cp -r ${{ steps.strings.outputs.build-output-dir }}/Examples/PreVEngineExample/assets build-linux-wayland-${{ matrix.compiler }}
        cp -r ${{ steps.strings.outputs.build-output-dir }}/Examples/PreVEngineExample/PreVEngineExample build-linux-wayland-${{ matrix.compiler }}
        cp -r ${{ steps.strings.outputs.build-output-dir }}/Examples/PreVEngineExample/*.so build-linux-wayland-${{ matrix.compiler }}

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-linux-wayland-${{ matrix.compiler }}
        path: build-linux-wayland-${{ matrix.compiler }}
        retention-days: 7

    - name: Run Tests
      run: |
        cd ${{ steps.strings.outputs.build-output-dir }}/PreVEngineTests
        ./PreVEngineTests
