name: Windows - CI Build/Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        include:
          - c_compiler: cl
            cpp_compiler: cl

    env:
      VULKAN_SDK: C:\VulkanSDK\

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Init Dawn submodule
      run: git -C PreVEngine/external/gfx submodule update --init third_party/dawn

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Ninja
      run: choco install ninja

    - name: Install Vulkan SDK
      run: |
        $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
        echo Version $ver
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/vulkansdk-windows-X64-$ver.exe" -OutFile VulkanSDK.exe
        echo Downloaded
        .\VulkanSDK.exe --root C:\VulkanSDK --accept-licenses --default-answer --confirm-command install
        echo "C:\VulkanSDK\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Compile Shaders
      run: |
        python3 Scripts/compile_shaders.py --spirv --max-view-count 1

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -G Ninja
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Create Artifact
      run: |
        mkdir build-win32
        cp -r ${{ steps.strings.outputs.build-output-dir }}/Examples/PreVEngineExample/assets build-win32
        cp -r ${{ steps.strings.outputs.build-output-dir }}/Examples/PreVEngineExample/PreVEngineExample.exe build-win32

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-win32
        path: build-win32
        retention-days: 7

    - name: Run Tests
      run: |
        cd ${{ steps.strings.outputs.build-output-dir }}/PreVEngineTests
        .\PreVEngineTests.exe


